spring:
  application:
    name: dubbo-service


dubbo:
  application:
    id: ${spring.application.name}
    name: ${dubbo.application.id}
  protocol:
    name: dubbo
    port: -1
    ssl-enabled: true
  registry:
    username: nacos
    password: nacos
    address: nacos://127.0.0.1:8848
    group: BUBBO_GROUP
    parameters:
      namespace: a61abd4c-ef96-42a5-99a1-616adee531f3
    enable-empty-protection: true
    protocol: nacos
  consumer:
    check: false
server:
  port: 9002